// Generated by CoffeeScript 1.6.3
(function($) {
  $.fn.extend({
    hmapi: function(options, arg, callback) {
      if (options && typeof options === "object") {
        options = $.extend({}, $.hmapi.defaults, options);
      }
      this.each(function() {
        return new $.hmapi(this, options, arg, callback);
      });
      return $(this);
    }
  });
  $.hmapi = function(elem, options, arg, callback) {
    /* get a room by Name*/

    var GetRoomById, getAllRooms, getRoomByName;
    getRoomByName = function(arg) {
      var data;
      data = {
        id: 0,
        name: arg,
        threshold: 1,
        currentClick: 0
      };
      $.hmapi._this.trigger("getRoomByName", data);
      return data;
    };
    /* get a room by Id*/

    GetRoomById = function(arg) {
      var data;
      data = {
        id: arg,
        name: "",
        threshold: 1,
        currentClick: 0
      };
      $.hmapi._this.trigger("GetRoomById", data);
      return data;
    };
    /* get all rooms*/

    getAllRooms = function() {
      var method, module, param;
      module = 'groups';
      method = 'GET';
      param = '';
      console.log($.hmapi.defaults.apiUrl + module);
      return $.ajax({
        type: method,
        data: param,
        cache: false,
        url: $.hmapi.defaults.apiUrl + module,
        async: true,
        dataType: "json",
        success: function(json) {
          console.log('result !!');
          console.log(json);
          $.hmapi._callback(json);
          return $.hmapi._this.trigger("getAllRooms", json);
        }
      });
    };
    /* ----------------*/

    /* var assignements*/

    /* ----------------*/

    $.hmapi._this = $(elem);
    if (typeof arg === 'function') {
      callback = arg;
    }
    $.hmapi._callback = callback;
    /* -----------------*/

    /* available methods*/

    /* -----------------*/

    if (options && typeof options === "string") {
      if (options === "getRoomByName") {
        getRoomByName(arg);
      } else if (options === "GetRoomById") {
        GetRoomById(arg);
      } else if (options === "getAllRooms") {
        getAllRooms();
      }
    }
  };
  $.hmapi.defaults = {
    apiUrl: "http://10.0.2.80:3000/"
  };
  $.hmapi._this = null;
  return $.hmapi._callback = null;
})(jQuery);
